### ISSUE TITLE
installing on LibO 24.2.3 on windows 11

### ISSUE THREAD

**Issue by Schmuser** [dennisfrancis/ClusterRows#4]
****Describe the bug**
i tryed to istall the extension and got   an error message:**

**--- beginn of message window**
<class 'TypeError'>: unsupported operand type(s) for |: 'type' and 'NoneType', traceback follows
  File "C:\Program Files\LibreOffice\program\pythonloader.py", line 147, in writeRegistryInfo
    mod = self.getModuleFromUrl( locationUrl )
  File "C:\Program Files\LibreOffice\program\pythonloader.py", line 102, in getModuleFromUrl
    exec(codeobject, mod.__dict__)
  File "C:\Users\h.schmueser.LJV-SH\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu22304113wdw.tmp_\ClusterRows-Windows.oxt\ClusterRows.py", line 28, in <module>
    from DataCluster import DataClusterImpl
  File "C:\Program Files\LibreOffice\program\uno.py", line 346, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
  File "C:\Users\h.schmueser.LJV-SH\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu22304113wdw.tmp_\ClusterRows-Windows.oxt\DataCluster.py", line 34, in <module>
    from perf import PerfTimer
  File "C:\Program Files\LibreOffice\program\uno.py", line 346, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
  File "C:\Users\h.schmueser.LJV-SH\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu22304113wdw.tmp_\ClusterRows-Windows.oxt\perf.py", line 20, in <module>
    class PerfTimer(object):
  File "C:\Users\h.schmueser.LJV-SH\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu22304113wdw.tmp_\ClusterRows-Windows.oxt\perf.py", line 21, in PerfTimer
    def __init__(self, name: str, showStart: bool = False, level: int = 0, logger: logging.Logger | None = None):

 at C:/cygwin64/home/buildslave/source/libo-core/pyuno/source/module/pyuno_runtime.cxx:950

**--second message page**
(com.sun.star.uno.RuntimeException) { { Message = "<class 'TypeError'>: unsupported operand type(s) for |: 'type' and 'NoneType', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 147, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 102, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\h.schmueser.LJV-SH\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu22304113wdw.tmp_\\ClusterRows-Windows.oxt\\ClusterRows.py\", line 28, in <module>\X000a    from DataCluster import DataClusterImpl\X000a  File \"C:\\Program Files\\LibreOffice\\program\\uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"C:\\Users\\h.schmueser.LJV-SH\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu22304113wdw.tmp_\\ClusterRows-Windows.oxt\\DataCluster.py\", line 34, in <module>\X000a    from perf import PerfTimer\X000a  File \"C:\\Program Files\\LibreOffice\\program\\uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"C:\\Users\\h.schmueser.LJV-SH\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu22304113wdw.tmp_\\ClusterRows-Windows.oxt\\perf.py\", line 20, in <module>\X000a    class PerfTimer(object):\X000a  File \"C:\\Users\\h.schmueser.LJV-SH\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu22304113wdw.tmp_\\ClusterRows-Windows.oxt\\perf.py\", line 21, in PerfTimer\X000a    def __init__(self, name: str, showStart: bool = False, level: int = 0, logger: logging.Logger | None = None):\X000a\X000a at C:/cygwin64/home/buildslave/source/libo-core/pyuno/source/module/pyuno_runtime.cxx:950", Context = (com.sun.star.uno.XInterface) @0 } }

**--end of message window**

**the curious thing is that i shall restart LibO, but the extension ist not visible, but in the list of installed extension. Trying to aktivate i got the same message.

I hope you can understand my description. This is my first action ever on GitHub.

Best whishes 
Heiko**

**Comment by dennisfrancis** [comment]
Hello, I'm able to reproduce this issue in Windows. Thanks for reporting. I'll look into this.

**Comment by dennisfrancis** [comment]
I've fixed this in master branch with https://github.com/dennisfrancis/ClusterRows/commit/44c4ce94168c0608e8c4de2aa411a337552ef210. I will upload a new release soon.
